### ISSUE TITLE
Dragon textures are bugged.

### ISSUE THREAD

**Issue by debian044** [ElCeejo/draconis#10]
I tested the new version of draconis on Minetest 5.4.1 and the texture seems to not fit onto the model properly.
![screenshot_20210821_103405](https://user-images.githubusercontent.com/78425255/130316016-68915943-c85c-4d44-89b2-d0c678815aa7.png)

**Comment by ElCeejo** [comment]
It appears that you didn't delete old textures, and because the new version uses the folders feature from 5.4 the old textures were not overwritten. Delete the old textures (and sounds) and reinstall to fix this.
