### ISSUE TITLE
Ice dracolily spawning

### ISSUE THREAD

**Issue by d5xtgr** [ElCeejo/draconis#13]
I've been unable to track down ice lilies in the game. Looking at mapgen.lua, line 853, it appears that the game tries to place them on blocks that don't exist - I can't find "default:dirt_with_snowy_grass" anywhere in Minetest documentation. Is it supposed to be "default:dirt_with_snow"?

I might suggest also placing them on "default:permafrost_with_moss", just for the sake of balance since the fiery lilies have multiple options.

**Comment by ronoaldo** [comment]
I also they have issues with the textures as well, I found some untextured ones that has spawned previously:

![screenshot_20220219_154928](https://user-images.githubusercontent.com/564649/154816059-91d9ef1b-181c-481c-8caa-250cd4be70bc.png)

**Comment by ElCeejo** [comment]
Dracolilies have been removed as of 1.2, so this is no longer an issue.
